export default {
  app: {
    SET_PAGE_TITLE: "SET_PAGE_TITLE"
  },
  movies: {
    GET_LIST_REQUEST: "GET_LIST_REQUEST",
    GET_LIST_RESPONSE: "GET_LIST_RESPONSE",
    GET_LIST_ERROR: "GET_LIST_ERROR",
    FILTER_SELECT: "FILTER_SELECT"
  },
  series: {
    GET_LIST_REQUEST: "GET_LIST_REQUEST",
    GET_LIST_RESPONSE: "GET_LIST_RESPONSE",
    GET_LIST_ERROR: "GET_LIST_ERROR",
    FILTER_SELECT: "FILTER_SELECT"
  }
};
