export default {
  app: {
    SET_PAGE_TITLE: "SET_PAGE_TITLE"
  },
  movies: {
    GET_LIST_REQUEST: "GET_LIST_REQUEST",
    GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
    GET_LIST_ERROR: "GET_LIST_ERROR"
  },
  series: {
    GET_LIST_REQUEST: "GET_LIST_REQUEST",
    GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
    GET_LIST_ERROR: "GET_LIST_ERROR"
  }
};
