export default {
  SET_PAGE_TITLE: "SET_PAGE_TITLE",
  GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
  GET_MOVIES_RESPONSE: "GET_MOVIES_RESPONSE",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
  GET_SERIES_REQUEST: "GET_SERIES_REQUEST",
  GET_SERIES_RESPONSE: "GET_SERIES_RESPONSE",
  GET_SERIES_ERROR: "GET_SERIES_ERROR"
};
